language: php
php:
  - 5.6

before_script:
  - composer self-update
  - composer install
  - ls -la
  - pwd
  - mkdir -p storage/app/dev
  - chmod -R 777 storage

script:
  - vendor/bin/security-checker security:check
  - phpunit